"""Changed_password_unique_to_false

Revision ID: 294a94c8ddbd
Revises: ce4cd1bc2347
Create Date: 2021-11-19 18:59:48.628883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294a94c8ddbd'
down_revision = 'ce4cd1bc2347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('password', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('password', 'user', ['password'], unique=False)
    # ### end Alembic commands ###
