"""Changed_permissions_to_hotel_owner_field

Revision ID: 703db21eb105
Revises: 99361e78c818
Create Date: 2021-11-19 19:51:11.923131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '703db21eb105'
down_revision = '99361e78c818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hotel_owner', sa.Boolean(), nullable=False))
    op.drop_column('user', 'permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('permission', mysql.ENUM('customer', 'hotel_owner'), nullable=False))
    op.drop_column('user', 'hotel_owner')
    # ### end Alembic commands ###
