"""Added enum fields in Hotel and User

Revision ID: 7eceab8410f6
Revises: 3f5184823d13
Create Date: 2021-10-24 00:48:52.290493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eceab8410f6'
down_revision = '3f5184823d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('transport_from_airport', sa.Enum('not_included', 'bus', 'car', name='transportenum'), nullable=True))
    op.add_column('user', sa.Column('permission', sa.Enum('customer', 'hotel_owner', name='userenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'permission')
    op.drop_column('hotel', 'transport_from_airport')
    # ### end Alembic commands ###
