"""Changed_user_table_a_bit

Revision ID: 99361e78c818
Revises: 294a94c8ddbd
Create Date: 2021-11-19 19:14:49.246607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99361e78c818'
down_revision = '294a94c8ddbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'birthday',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'permission',
               existing_type=mysql.ENUM('customer', 'hotel_owner'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'permission',
               existing_type=mysql.ENUM('customer', 'hotel_owner'),
               nullable=True)
    op.alter_column('user', 'birthday',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
