"""Initial

Revision ID: a2f7fcf52566
Revises: 
Create Date: 2021-12-03 04:51:30.371241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f7fcf52566'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city_image', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('population', sa.INTEGER(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service', sa.String(length=150), nullable=False),
    sa.Column('cost', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('token_black_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('hotel_owner', sa.Boolean(), nullable=False),
    sa.Column('location_link', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('famous_place',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city_id', sa.INTEGER(), nullable=True),
    sa.Column('famous_place', sa.String(length=50), nullable=False),
    sa.Column('entrance_fee', sa.INTEGER(), nullable=False),
    sa.Column('famous_place_image', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('hotel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city_id', sa.INTEGER(), nullable=True),
    sa.Column('hotel', sa.String(length=100), nullable=False),
    sa.Column('stars', sa.INTEGER(), nullable=False),
    sa.Column('image_link', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('apartment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hotel_id', sa.INTEGER(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('room_capacity', sa.INTEGER(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('floor', sa.INTEGER(), nullable=False),
    sa.Column('cost', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.String(length=750), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hotel_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('review', sa.String(length=500), nullable=True),
    sa.Column('mark', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('apartment_id',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('apartment_id', sa.INTEGER(), nullable=True),
    sa.Column('image', sa.String(length=750), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('reserve',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reserve_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('reserve_start_date', sa.DateTime(), nullable=True),
    sa.Column('reserve_finish_date', sa.DateTime(), nullable=True),
    sa.Column('reserve_cost', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['reserve_id'], ['apartment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('reserve_service',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reserve_id', sa.INTEGER(), nullable=False),
    sa.Column('service_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['reserve_id'], ['reserve.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserve_service')
    op.drop_table('reserve')
    op.drop_table('apartment_id')
    op.drop_table('review')
    op.drop_table('apartment')
    op.drop_table('hotel')
    op.drop_table('famous_place')
    op.drop_table('user')
    op.drop_table('token_black_list')
    op.drop_table('service')
    op.drop_table('city')
    # ### end Alembic commands ###
