"""Added_TokenBlackList_table

Revision ID: c2d76eeeeb15
Revises: 703db21eb105
Create Date: 2021-11-20 00:13:10.270320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d76eeeeb15'
down_revision = '703db21eb105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_black_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_black_list')
    # ### end Alembic commands ###
