"""Changed_famous_place_data

Revision ID: e280451841bb
Revises: 8e2d4102f277
Create Date: 2021-11-10 23:22:04.361086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e280451841bb'
down_revision = '8e2d4102f277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('famous_place', sa.Column('famous_place_image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('famous_place', 'famous_place_image')
    # ### end Alembic commands ###
